App/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using App.Core;
using App.IBLL;
using App.Models;
using App.Models.Sys;
using Microsoft.Practices.Unity;

namespace App.Controllers
{
    
    public class HomeController : BaseController
    {
        [Dependency]
        public IHomeBLL HomeBll { get; set; }

        [SupportFilter]
        public ActionResult Index()
        {
            ViewBag.UserName = GetUserTrueName();
            return View();
        }

        [HttpPost]
        public JsonResult GetTree(string id)
        {
            if (GetAccount() != null)
            {
                List<SysModule> menu = HomeBll.GetMenuByPersonId(GetUserId(), id);
                var jsonData = (from m in menu
                                select
                                    new
                                    {
                                        id = m.Id,
                                        text = m.Name,
                                        value = m.Url,
                                        showcheck = false,
                                        complete = false,
                                        isexpand = false,
                                        checkstate = 0,
                                        hasChildren = m.IsLast ? false : true,
                                        Icon = m.Iconic
                                    }
                    ).ToArray();
                return Json(jsonData, JsonRequestBehavior.AllowGet);
            }
            return Json("0", JsonRequestBehavior.AllowGet);
        }
    }
}

App/Controllers/SysSampleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using App.Common;
using App.Core;
using App.IBLL;
using App.Models.Sys;
using Microsoft.Practices.Unity;

namespace App.Controllers
{
    
    public class SysSampleController : BaseController
    {
        [Dependency]
        public ISysSampleBLL m_bll { get; set; }

        [SupportFilter]
        // GET: SysSample
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult GetList(GridPager pager, string queryStr)
        {
            List<SysSampleModel> list = m_bll.GetList(ref pager, queryStr);
            var json = new
            {
                total = pager.totalRows,
                rows = (from r in list
                        select new SysSampleModel()
                        {
                            Id = r.Id,
                            Name = r.Name,
                            Age = r.Age,
                            Bir = r.Bir,
                            Photo = r.Photo,
                            Note = r.Note,
                            CreateTime = r.CreateTime
                        }).ToArray()
            };
            return MyJson(json, JsonRequestBehavior.AllowGet, "yyyy-MM-dd HH:mm:ss");
        }

        [SupportFilter]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [SupportFilter]
        public JsonResult Create(SysSampleModel model)
        {
            ValidationErrors errors = new ValidationErrors();
            if (ModelState.IsValid)
            {
                if (m_bll.Create(ref errors, model))
                {
                    LogHandler.WriteServiceLog("虚拟用户", "Id:" + model.Id + ",Name:" + model.Name, "成功", "创建", "样例程序");
                    return Json(JsonHandler.CreateMessage(1, "插入成功"), JsonRequestBehavior.AllowGet);
                }
            }
            LogHandler.WriteServiceLog("虚拟用户", "Id:" + model.Id + ",Name:" + model.Name + "," + errors.Error, "失败", "创建", "样例程序");
            return Json(JsonHandler.CreateMessage(0, "插入失败" + errors.Error), JsonRequestBehavior.AllowGet);
        }

        [SupportFilter]
        public ActionResult Edit(string id)
        {
            SysSampleModel entity = m_bll.GetById(id);
            return View(entity);
        }

        [HttpPost]
        [SupportFilter]
        public JsonResult Edit(SysSampleModel model)
        {
            ValidationErrors errors = new ValidationErrors();
            if (ModelState.IsValid)
            {
                if (m_bll.Edit(ref errors, model))
                {
                    LogHandler.WriteServiceLog("虚拟用户", "Id:" + model.Id + ",Name:" + model.Name, "成功", "编辑", "样例程序");
                    return Json(JsonHandler.CreateMessage(1, "修改成功"), JsonRequestBehavior.AllowGet);
                }
            }
            LogHandler.WriteServiceLog("虚拟用户", "Id:" + model.Id + ",Name:" + model.Name + "," + errors.Error, "失败", "编辑", "样例程序");
            return Json(JsonHandler.CreateMessage(0, "修改失败" + errors.Error), JsonRequestBehavior.AllowGet);
        }

        [SupportFilter]
        public ActionResult Details(string id)
        {
            SysSampleModel entity = m_bll.GetById(id);
            return View(entity);
        }

        [HttpPost]
        [SupportFilter]
        public JsonResult Delete(string id)
        {
            ValidationErrors errors = new ValidationErrors();
            if (!string.IsNullOrWhiteSpace(id))
            {
                if (m_bll.Delete(ref errors, id))
                {
                    LogHandler.WriteServiceLog("虚拟用户", "Id:" + id, "成功", "删除", "样例程序");
                    return Json(JsonHandler.CreateMessage(1, "删除成功"), JsonRequestBehavior.AllowGet);
                }
            }
            LogHandler.WriteServiceLog("虚拟用户", "Id:" + id + "," + errors.Error, "成功", "删除", "样例程序");
            return Json(JsonHandler.CreateMessage(0, "删除失败" + errors.Error), JsonRequestBehavior.AllowGet);
        }
    }
}

App/Views/Home/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width" />

    @Styles.Render("~/Content/themes/gray/css")
    @Styles.Render("~/Content/wdtree")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body class="easyui-layout">

    <div id="OverTimeLogin" class="easyui-dialog" data-options="closed:true,modal:true">
        <iframe width="726px" height="497px" frameborder="0" scrolling="no" id="iOverTimeLogin"></iframe>
    </div>

    <div data-options="region:'north',border:false,split:true" style="height: 60px">
        <div class="define-head">
            <div class="define-logo">
                <div id="LoginTopLine">System Manager</div>
                <div id="LoginBottomLine">MVC5+EF6.0+EasyUI</div>
            </div>
            <div class="define-account">
                <div id="LoginTopLine"><span>@ViewBag.UserName<b>&nbsp;欢迎您!</b></span></div>
                <div id="LoginBottomLine">
                    @using (Html.BeginForm("LogOut", "Account", "Post"))
                    {
                        @Html.AntiForgeryToken()
                        <a href="#" onclick="javascripts: $('form').submit();">安全退出</a>
                    }
                </div>
            </div>
        </div>
    </div>

    <div data-options="region:'south',border:true" style="height: 20px;">
        <div class="define-bottom">
            I'm foot!
        </div>
    </div>

    <div data-options="region:'west',split:true" title="菜单列表" style="width: 200px;background-color: #fff; overflow: auto; padding-top: 2px;">
        <div id="RightTree" style="background-color: #fff">
            <div class="panel-loading">加载中...</div>
        </div>
    </div>
    <div data-options="region:'center',border:false">
        <div id="mainTab" class="easyui-tabs" data-options="fit:true">
            <div title="我的桌面" data-options="closable:true" style="overflow: hidden; background-color: #fff">
                <iframe frameborder="0" scrolling="auto" src="@Url.Action("Index","SysSample")" style="width: 100%; height: 100%;"></iframe>
            </div>
        </div>
    </div>

    <div id="tab_menu" class="easyui-menu" style="width: 150px;">
        <div id="tab_menu-tabrefresh" data-options="iconCls:'icon-reload'">刷新</div>
        <div id="tab_menu-openFrame">在新的窗体打开</div>
        <div id="tab_menu-tabcloseall">关闭所有</div>
        <div id="tab_menu-tabcloseother">关闭其他标签</div>

        <div class="menu-sep"></div>

        <div id="tab_menu-tabcloseright">关闭右边</div>
        <div id="tab_menu-tabcloseleft">关闭左边</div>
        <div id="tab_menu-tabclose" data-options="iconCls:'icon-remove'">关闭</div>

        <div id="menu" class="easyui-menu" style="width: 150px;">

        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/easyui")
    @Scripts.Render("~/bundles/wdtree")
    <script src="~/Scripts/app/home.js"></script>
</body>
</html>